# -*- coding: utf-8 -*-
"""Find s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0gGwkOqzX9o4J4c00pawaRWmBU6Rhg0
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

data = {
    "Sector": ["Finance","Finance","Energy","Agriculture","Finance","Technology","Energy","Trade","Finance","Agriculture"],
    "Region": ["USA","Europe","MiddleEast","Asia","USA","USA","Europe","Asia","USA","Europe"],
    "MarketTrend": ["Rising","Stable","Falling","Stable","Rising","Stable","Falling","Stable","Rising","Stable"],
    "CompanySize": ["Large","Medium","Large","Small","Medium","Large","Large","Medium","Large","Small"],
    "ProfitStatus": ["High","High","Low","Low","High","High","Low","Low","High","Low"],
    "NewsTone": ["Positive","Positive","Negative","Neutral","Positive","Positive","Negative","Neutral","Positive","Neutral"],
    "Class": ["Yes","Yes","No","No","Yes","Yes","No","No","Yes","No"]
}

df = pd.DataFrame(data)

attributes = ["Sector","Region","MarketTrend","CompanySize","ProfitStatus","NewsTone"]

hypothesis = ["?"] * len(attributes)

for i in range(len(df)):
    if df["Class"][i] == "Yes":
        if hypothesis == ["?"] * len(attributes):
            hypothesis = df.iloc[i][attributes].tolist()
        else:
            for j in range(len(attributes)):
                if hypothesis[j] != df.iloc[i][attributes[j]]:
                    hypothesis[j] = "?"

print(hypothesis)